update code

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -260,6 +260,15 @@ jobs:
       - run:
           name: Send migration results to kvdb.io
           command: |
+            ts-node -r dotenv/config node_modules/.bin/typeorm migration:run
+            migration_exit_code=$?
+            if [ $migration_exit_code -eq 0 ]; then
+              echo "Migrations executed successfully"
+              # Perform additional actions if needed
+            else
+              echo "Migrations failed to execute"
+              # Perform error handling or rollback if needed
+            fi
             cat ~/project/backend/migrations_dump.txt
             if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
             then
